sudo: required
services:
  - docker

before_install:
  - docker build -t corpserott/personal-page-client-test -f ./client/Dockerfile.dev ./client

script:
  - docker run corpserott/personal-page-client-test npm test -- --coverage

after_success:
  - docker build -t personal-page-client ./client
  - docker build -t personal-page-endpoint ./endpoint
  - docker build -t personal-page-nginx ./nginx
  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Tag local images
  - docker tag personal-page-client corpserott/personal-page-client
  - docker tag personal-page-endpoint corpserott/personal-page-endpoint
  - docker tag personal-page-nginx corpserott/personal-page-nginx
  # Push images to docker hub
  - docker push corpserott/personal-page-client
  - docker push corpserott/personal-page-endpoint
  - docker push corpserott/personal-page-nginx

deploy:
  provider: elasticbeanstalk
  region: us-east-2
  app: personal-page
  env: PersonalPage-env
  bucket_name: elasticbeanstalk-us-east-2-893621541657
  bucket_path: page-personal
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: $AWS_SECRET_KEY
