sudo: required
services:
  - docker

before_install:
  - docker build -t personal-page/client-test -f ./client/Dockerfile.dev ./client

script:
  - docker run personal-page/client-test npm test -- --coverage

after_success:
  - docker build -t personal-page/client ./client
  - docker build -t personal-page/endpoint ./endpoint
  - docker build -t personal-page/nginx ./nginx
  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Push images to docker hub
  - docker push personal-page/client
  - docker push personal-page/endpoint
  - docker push personal-page/nginx

deploy:
  provider: elasticbeanstalk
  region: us-east-2
  app: personal-page
  env: PersonalPage-env
  bucket_name: arn:aws:s3:::elasticbeanstalk-us-east-2-893621541657
  bucket_path: personal-page
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: $AWS_SECRET_KEY
