version: '3.4'
services:
  client:
    build:
      dockerfile: Dockerfile.dev
      context: ./client
    ports:
      - "3000:3000"
    volumes:
      - /usr/app/node_modules
      - ./client:/usr/app
  endpoint:
    build:
      dockerfile: Dockerfile.dev
      context: ./endpoint
    volumes:
      - /usr/app/node_modules
      - ./endpoint:/usr/app
    environment:
      - PGUSER=postgres
      - PGHOST=postgres
      - PGDATABASE=postgres
      - PGPASSWORD=postgres_password
      - PGPORT=5432
  nginx:
    restart: always
    build:
      dockerfile: Dockerfile
      context: ./nginx
    ports:
      - '3050:80'
  database:
    image: 'postgres:latest'
